openapi: 3.0.0
info:
  title: Football Competition Management API
  version: 1.0.0
  description: API for managing football competitions, teams, and players.

paths:
  /competitions:
    post:
      summary: "Create a new competition"
      description: "This endpoint allows you to create a new football competition."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitionInput'
      responses:
        '201':
          description: "Competition created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Competition'
        '400':
          description: "Bad request"
          
    get:
      summary: "Get a list of competitions"
      description: "Retrieve a paginated list of football competitions."
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
            default: 1
          description: "Page number for pagination"
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
            default: 10
          description: "Number of competitions per page"
      responses:
        '200':
          description: "A list of competitions"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
        '400':
          description: "Bad request"

components:
  schemas:
    Competition:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "CAN"
        country_or_continent:
          type: string
          example: "RDC"

    CompetitionInput:
      type: object
      properties:
        name:
          type: string
          example: "CAN"
        country_or_continent:
          type: string
          example: "RDC"
      required:
        - name
        - country_or_continent
